version: '3.7'

services:
    postgres:
      build:
        context: ./postgres
      ports:
      - 5432:5432
      restart: on-failure
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_HOST_AUTH_METHOD=trust

    sqlserver:
      build:
        context: ./sqlserver
      ports:
      - 1433:1433
      restart: on-failure
      environment:
        - SA_PASSWORD=yourStrong(!)Password
        - ACCEPT_EULA=Y
        - MSSQL_PID=Developer
        - MSSQL_USER=SA

    console:
      build:
        context: ./console
      depends_on:
        - postgres
        - sqlserver
      restart: on-failure
      volumes:
        - ../databases:/work/databases:rw
        - ../__init__.py:/work/__init__.py:ro
        - ../main.py:/work/main.py:rw
      environment:
        - RDS_ENDPOINT=postgres
        - DBUSER=postgres
        - PORT=5432
